apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitled-registry-credentials
  namespace: ci
spec:
  encryptedData:
    IBM_ENTITLED_REGISTRY_PASSWORD: AgDLbe5T24r+lCt6oOtNu0+sB/yGbiDRZstOp8VNXlH0+Hinx0r7HmreubS6WBuDEjEoYDqlU5xhTjrXVx87Qd5EvM2PAe/ljG+xvqnWlqzURg+UjsihbEWX+In3/vzN5QyFVD5Yht2HRl5YqmmEbubq81Yax+CjiDrriL5GvG6ZlD1oe4AKnCcv42gf5nxMS2qPMTRNn1JhI9NehpN2PjpMwLt0E2lZPAYseY4AxwVgAGD+kkDRM9271qH62xnkujWwOlXzhjl9MZR44HiGIXZiiUIBUFx8Swd4hztyVWDF8hu/O1thnLrcjWvlVuas4CImfxxaUhiC9kZX0jeRItagW8+YV1Y1UFOwB+b4DYFvUIVKvBYd2b046ZtcxQsE6vpOXIFULXb3V+B0MP/w3mdbdNFkKNRGooR/EDNYFr35gUwLULx3hmJlqS8IFSMPaS7GTaGRZClYKpPcNfztuaMtdEB83hsHcA4x+XK/2dZS4gIeSBJwqKOm++82aV/kuXNWMKuw0aUwy994UVcg5xb/uB/L8IEfkAW7LXgrXnWwYgn2EQescS68zYj8tW5nMhP01dbJZP9Tr8y37KDKOoS7ASRu/ekki7eFCFfrpkUSathcU9hHLJJlr7O6YxmRRfmNXZ7VJ/4eIgMECg6p4WxzvrNQffOZZPRPxN9zJlezQgeeevBN9tiNBdHVYK/HtwizYMP1t37n7e8ykxrIX9BQduAk5iaOnUTO6Q3ylJhac96Ldr0DWsVb3W+RnQ88VaPK6JNwSfs4ocufROrhbtGH2rF+cuqm5P1czjQkWpA0FVb4yK/RUdr8pNXsPHLIn2Z5NwMxqqQ4aor0b+crSi8iSywAnvz7eEu2yFXiOIyVDJ7Z3i4gjN+0s7rYm4bFVjEhcoCgyMdE56zp38/flYG0knTe7t0gx5JU4cA/PmOZEw==
    IBM_ENTITLED_REGISTRY_USER: AgBcB94Io5DoCxK+uVj6kOO8GIgB00jSiupTU9hGtJt0+DW33yE/FVEJKoHoyqnKOL8Jj9oSGd6ql9veswCYfTLe3Jy0yE93V6NzYyUnszf1gpYjmEIjfa0uTGrZKnuM+8C948UMkraAanTyg0qa6sFMFMa+0lR/nRaKaE1XWWWMJSthJo4dDiqcZnu/sV5R0U5uWTogArx95DFADEwQ2cwCd7vYhZB8iau9dJXY94UzwXEXtHWUEod076QJdeh97vYd5/wB9lJO+k7dA96iOWARgNO3MhcNgCzrse7TaOHFnNp4uBakf6vCPCnX1TFgOC5lqf4YmhDaRKxePR/GVCFTZb8AOSh3ZUMiJDJCq7ZEPbvwHmDNjtqMVH+sHL0uryFKn5olGRQzHs9+qBAB8TF+Q9IMEDkpdPJTkMRq+0BenCxjO37wTyOqafFh65S3kRsNjtdV0RUEnHqmjSf3sEhkmPRIBaiitlS6PxUQn5sW87RqVh26+e7kSqBS4xmzgCZSGzkXT59hWHiUj20Xv5G2LG7NW+fRbS5FTCpWmgfJlC+PZbhIvJDHZRvc4+4TGTr9/u1zMezxPai36ICf7omufgMuhmXcrraglE/d1H0Ml/ntqVlbVVsWvlHDZG90k/5lXQy9iPIVRz3EJw4pBt0PfnHLDUQXnCjNwF8J+xAZY6n0cJxz4a0tpd3fzBnIW1fkmg==
  template:
    metadata:
      creationTimestamp: null
      name: ibm-entitled-registry-credentials
      namespace: ci

